# Generated by Django 4.2.7 on 2023-12-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0002_calender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latestnews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=100)),
            ],
        ),
    ]
